apiVersion: v1
kind: Service
metadata:
  name: blinds-backend-service
  namespace: home-manager
  labels:
    app: blinds-backend
spec:
  type: ClusterIP
  selector:
    app: blinds-backend
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
