apiVersion: v1
kind: Service
metadata:
  name: blinds-control-service
  namespace: home-manager
  labels:
    app: blinds-control
spec:
  type: NodePort
  selector:
    app: blinds-control
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30333
  sessionAffinity: ClientIP
